"""Shared API command metadata for GUI, headless, and web clients."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

from .protocol import protocol_named_command_names


SUPPORTED_COMMANDS: tuple[str, ...] = (
    "protocol.hello",
    "system.ping",
    "system.heartbeat",
    "system.status",
    "motor.status",
    "ptm.status",
    "system.commands",
    "protocol.catalog",
    "serial.ports",
    "serial.settings",
    "serial.connect",
    "serial.disconnect",
    "serial.scan",
    "serial.scan_cancel",
    "serial.auto_reconnect",
    "motion.jog",
    "motion.stop",
    "motion.force_stop",
    "motion.absolute",
    "motion.goto",
    "motion.tolerance",
    "motion.completion_config",
    "position.get",
    "monitor.set",
    "recipe.list",
    "recipe.select",
    "recipe.export",
    "recipe.import",
    "recipe.upsert",
    "recipe.delete",
    "point.upsert",
    "point.select",
    "point.delete",
    "point.reorder",
    "point.goto",
    *protocol_named_command_names(),
    "lens.motion",
    "aux.set",
    "preset.set",
    "preset.call",
    "preset.goto",
    "preset.clear",
    "preset.delete",
    "preset.speed_adjust",
    "raw.describe",
    "scan.set_point",
    "scan.start",
    "scan.stop",
    "scan.speed",
    "scan.speed_adjust",
    "cruise.start",
    "cruise.stop",
    "cruise.speed",
    "home.auto",
    "home.after",
    "home.start",
    "laser.arm",
    "laser.on",
    "laser.off",
    "laser.pulse",
    "device.query",
    "maintenance.self_check",
    "maintenance.restart",
    "maintenance.factory_default",
    "maintenance.power_on_self_check",
    "raw.send",
)


DANGEROUS_COMMANDS: tuple[str, ...] = (
    "preset.set",
    "preset.clear",
    "preset.delete",
    "pelco.remote_reset",
    "zero.set",
    "device.remote_baud",
    "maintenance.self_check",
    "maintenance.restart",
    "maintenance.factory_default",
    "maintenance.power_on_self_check",
    "protocol.command",
    "raw.send",
)


COMMAND_ENUMS: dict[str, list[str]] = {
    "action": ["zoom_in", "zoom_out", "focus_near", "focus_far", "iris_open", "iris_close"],
    "pan": ["stop", "left", "right"],
    "tilt": ["stop", "up", "down"],
    "direction": ["faster", "slower"],
    "point": ["start", "end"],
    "type": ["pan", "tilt", "zoom", "focus", "device"],
    "kind": [
        "line_lock_phase",
        "white_balance_rb",
        "white_balance_mg",
        "gain",
        "auto_iris_level",
        "auto_iris_peak",
    ],
    "camera_mode": ["manual", "auto", "off"],
    "scan_mode": ["vendor", "zone"],
    "auto_mode": ["auto", "off"],
    "home_action": ["preset1", "cruise1"],
}


COMMAND_TEMPLATES: dict[str, dict[str, Any]] = {
    "protocol.hello": {"version": "1.0", "client_name": "PLC"},
    "system.ping": {},
    "system.heartbeat": {"sequence": 1},
    "system.status": {},
    "motor.status": {},
    "ptm.status": {},
    "system.commands": {},
    "protocol.catalog": {},
    "serial.ports": {},
    "serial.settings": {"port": "", "baudrate": 9600, "address": 1},
    "serial.connect": {"port": "", "baudrate": 9600, "address": 1, "auto_reconnect": True},
    "serial.disconnect": {},
    "serial.scan": {"baudrates": [9600], "first_address": 1, "last_address": 1, "timeout_ms": 200},
    "serial.scan_cancel": {},
    "serial.auto_reconnect": {
        "enabled": True,
        "baudrates": [9600],
        "first_address": 1,
        "last_address": 16,
        "timeout_ms": 200,
        "retry_interval_s": 3.0,
        "health_interval_s": 2.0,
    },
    "motion.jog": {"pan": "right", "tilt": "stop", "pan_level": 5, "tilt_level": 5, "duration_ms": 500},
    "motion.stop": {},
    "motion.force_stop": {},
    "motion.absolute": {"pan": 0.0, "tilt": 0.0},
    "motion.goto": {"recipe_id": "", "point_id": ""},
    "motion.tolerance": {"tolerance_deg": 0.2, "stable_samples": 3, "timeout_s": 30},
    "motion.completion_config": {"tolerance_deg": 0.2, "stable_samples": 3, "timeout_s": 30},
    "position.get": {"refresh": True},
    "monitor.set": {"enabled": True, "interval_ms": 500},
    "recipe.list": {},
    "recipe.select": {"recipe_id": ""},
    "recipe.export": {"recipe_id": ""},
    "recipe.import": {"document": {}},
    "recipe.upsert": {"name": "Recipe", "description": ""},
    "recipe.delete": {"recipe_id": ""},
    "point.upsert": {
        "recipe_id": "",
        "name": "P1",
        "pan": 0.0,
        "tilt": 0.0,
        "dwell_ms": 0,
        "enabled": True,
        "note": "",
    },
    "point.select": {"recipe_id": "", "point_id": ""},
    "point.delete": {"recipe_id": "", "point_id": ""},
    "point.reorder": {"recipe_id": "", "ordered_ids": []},
    "point.goto": {"recipe_id": "", "point_id": ""},
    "drawing.list": {},
    "drawing.get": {"drawing_id": ""},
    "drawing.delete": {"drawing_id": "", "confirm": True},
    "drawing.select_point_set": {"drawing_id": "", "point_file": ""},
    "drawing.point_upsert": {
        "drawing_id": "",
        "point_id": "",
        "label": "P1",
        "x": 0.0,
        "y": 0.0,
        "z": 0.0,
        "calibration": False,
        "pan": None,
        "tilt": None,
    },
    "drawing.point_delete": {"drawing_id": "", "point_id": ""},
    "drawing.point_reorder": {"drawing_id": "", "ordered_ids": []},
    "drawing.calibrate": {"drawing_id": ""},
    "drawing.estimate_xy": {"drawing_id": "", "pan": 0.0, "tilt": 0.0},
    "drawing.estimate_recipe": {"drawing_id": "", "recipe_id": ""},
    "drawing.export_recipe": {"drawing_id": "", "recipe_id": ""},
    "drawing.import_recipe": {"drawing_id": "", "recipe_id": ""},
    "protocol.command": {"command1": 0, "command2": 15, "data1": 0, "data2": 0, "confirm": True},
    "motion.relative": {"pan_delta": 1.0},
    "zoom.set": {"value": 1000},
    "focus.set": {"value": 1000},
    "pelco.flip": {},
    "pelco.zero_pan": {},
    "pelco.remote_reset": {"confirm": True},
    "zone.set_start": {"zone": 1},
    "zone.set_end": {"zone": 1},
    "screen.write_char": {"column": 0, "char": "A"},
    "screen.write_text": {"column": 0, "text": "TEST"},
    "screen.clear": {},
    "alarm.ack": {"alarm": 1, "subopcode": 0},
    "pattern.record_start": {"pattern": 1},
    "pattern.record_stop": {},
    "pattern.run": {"pattern": 1},
    "lens.zoom_speed": {"speed": 2},
    "lens.focus_speed": {"speed": 2},
    "camera.power": {"enabled": True},
    "camera.scan": {"mode": "auto"},
    "camera.auto_focus": {"mode": "auto"},
    "camera.auto_iris": {"mode": "auto"},
    "camera.agc": {"mode": "auto"},
    "camera.backlight": {"enabled": False},
    "camera.auto_white_balance": {"enabled": True},
    "camera.phase_delay": {},
    "camera.shutter": {"value": 0},
    "camera.adjust": {"kind": "gain", "value": 0, "delta": False},
    "preset.scan": {"dwell": 5},
    "zero.set": {"confirm": True},
    "magnification.set": {"value": 1000, "subopcode": 0},
    "magnification.query": {},
    "echo.activate": {},
    "device.remote_baud": {"code": 2, "subopcode": 0, "confirm": True},
    "device.query_diagnostics": {},
    "cruise.interval": {"value": 1},
    "home.time": {"value": 1},
    "lens.motion": {"action": "zoom_in"},
    "aux.set": {"number": 1, "enabled": True},
    "preset.set": {"number": 1, "confirm": True},
    "preset.call": {"number": 1},
    "preset.goto": {"number": 1},
    "preset.clear": {"number": 1, "confirm": True},
    "preset.delete": {"number": 1, "confirm": True},
    "preset.speed_adjust": {"direction": "faster"},
    "raw.describe": {"hex": "FF 01 00 51 00 00 52"},
    "scan.set_point": {"point": "start"},
    "scan.start": {"mode": "vendor"},
    "scan.stop": {"mode": "vendor"},
    "scan.speed": {"pan_speed": 63, "tilt_speed": 63},
    "scan.speed_adjust": {"direction": "faster"},
    "cruise.start": {"track": 1},
    "cruise.stop": {},
    "cruise.speed": {"pan_speed": 63, "tilt_speed": 63},
    "home.auto": {"enabled": False},
    "home.after": {"action": "cruise1"},
    "home.start": {},
    "laser.arm": {"enabled": True},
    "laser.on": {},
    "laser.off": {},
    "laser.pulse": {"duration_ms": 500},
    "device.query": {"type": "pan"},
    "maintenance.self_check": {"confirm": True},
    "maintenance.restart": {"confirm": True},
    "maintenance.factory_default": {"confirm": True},
    "maintenance.power_on_self_check": {"enabled": False, "confirm": True},
    "raw.send": {"hex": "FF 01 00 51 00 00 52", "confirm": True},
}


COMMAND_GROUP_GUIDE: dict[str, str] = {
    "system": "서버 상태와 지원 기능을 확인합니다.",
    "serial": "Pelco-D 직렬 포트, 통신 속도, 장치 주소를 설정합니다.",
    "motion": "Pan/Tilt를 수동 또는 절대·상대 위치로 이동합니다.",
    "position": "장치가 보고한 현재 Pan/Tilt 위치를 조회합니다.",
    "monitor": "주기적인 위치 조회를 켜거나 끕니다.",
    "recipe": "운전 레시피를 조회·저장·가져오기 합니다.",
    "point": "레시피 포인트를 편집하거나 해당 위치로 이동합니다.",
    "drawing": "도면, 좌표 파일, 캘리브레이션 데이터를 관리합니다.",
    "pelco": "Pelco-D 확장 명령입니다. 장치별 지원 여부를 확인하세요.",
    "preset": "장치 내부 프리셋을 설정·호출·삭제합니다.",
    "scan": "라인/영역 스캔과 속도를 설정합니다.",
    "cruise": "장치 내부 크루즈 기능을 제어합니다.",
    "camera": "카메라 전원, 초점, 조리개, 영상 보정을 제어합니다.",
    "lens": "줌·초점·조리개와 렌즈 속도를 제어합니다.",
    "zone": "현재 위치를 영역 시작점 또는 끝점으로 저장합니다.",
    "pattern": "장치 내부 패턴 녹화와 재생을 제어합니다.",
    "screen": "장치 화면 문자 표시를 제어합니다.",
    "device": "장치 정보 조회와 원격 통신 설정을 수행합니다.",
    "maintenance": "재시작·초기화 등 주의가 필요한 유지보수 명령입니다.",
    "laser": "레이저 모듈 연결과 안전 상태를 제어합니다.",
    "raw": "직접 만든 Pelco-D 프레임을 검증하거나 전송합니다.",
    "protocol": "Pelco-D 원시 명령 바이트를 직접 지정합니다.",
}


COMMAND_GUIDE: dict[str, str] = {
    "motion.jog": "방향 비트와 Pan/Tilt 속도(0x00~0x3F)를 사용해 일정 시간 움직입니다.",
    "motion.stop": "모든 방향 비트를 끈 정지 프레임을 즉시 전송합니다.",
    "motion.absolute": "Pan 0~359.99°, Tilt -60~60°의 절대 위치로 이동합니다.",
    "motion.relative": "현재 위치를 기준으로 Pan 각도를 상대 이동합니다.",
    "position.get": "0x51/0x53 질의로 Pan/Tilt 값을 조회합니다. refresh=false면 캐시값만 반환합니다.",
    "pelco.flip": "Go To Preset 계열의 180° Flip 명령을 전송합니다.",
    "pelco.zero_pan": "장치가 지원할 때 Pan 영점 위치로 이동합니다.",
    "pelco.remote_reset": "장치를 원격 재설정합니다. 실행 전 확인이 필요합니다.",
    "preset.set": "현재 위치를 장치 내부 프리셋 번호에 저장합니다.",
    "preset.call": "장치 내부 프리셋 번호를 호출합니다.",
    "preset.clear": "장치 내부 프리셋 번호를 삭제합니다.",
    "zoom.set": "16비트 값으로 줌 절대 위치를 설정합니다.",
    "focus.set": "16비트 값으로 초점 절대 위치를 설정합니다.",
    "lens.motion": "Zoom/Focus/Iris를 누르는 동안 동작시키는 표준 명령입니다.",
    "lens.zoom_speed": "장치가 지원하는 줌 속도 단계를 설정합니다.",
    "lens.focus_speed": "장치가 지원하는 초점 속도 단계를 설정합니다.",
    "camera.auto_focus": "자동 초점 모드를 켜거나 끕니다.",
    "camera.auto_iris": "자동 조리개 모드를 켜거나 끕니다.",
    "camera.agc": "자동 게인 제어 모드를 설정합니다.",
    "camera.backlight": "역광 보정 기능을 켜거나 끕니다.",
    "camera.auto_white_balance": "자동 화이트밸런스를 켜거나 끕니다.",
    "scan.start": "라인 또는 Zone 스캔을 시작합니다.",
    "scan.stop": "실행 중인 라인 또는 Zone 스캔을 정지합니다.",
    "pattern.record_start": "지정 패턴의 동작 기록을 시작합니다.",
    "pattern.record_stop": "진행 중인 패턴 기록을 종료합니다.",
    "pattern.run": "저장된 패턴 번호를 재생합니다.",
    "device.query": "Pan/Tilt/Zoom/Focus 또는 장치 종류를 질의합니다.",
    "device.remote_baud": "장치의 원격 통신 속도 코드를 변경합니다. 연결이 끊길 수 있습니다.",
    "maintenance.restart": "장치를 재시작합니다. 실행 전 확인이 필요합니다.",
    "maintenance.factory_default": "장치 설정을 공장 초기값으로 되돌립니다.",
    "protocol.command": "cmnd1, cmnd2, data1, data2를 직접 지정하고 체크섬을 생성합니다.",
    "raw.describe": "7바이트 Pelco-D 프레임을 검증하고 의미를 표시하며 전송하지는 않습니다.",
    "raw.send": "7바이트 Pelco-D 프레임을 그대로 전송합니다. 체크섬과 장치 지원 여부를 확인하세요.",
}


def supported_command_names() -> list[str]:
    return list(SUPPORTED_COMMANDS)


def command_templates(commands: list[str] | tuple[str, ...] | None = None) -> dict[str, dict[str, Any]]:
    selected = commands or SUPPORTED_COMMANDS
    return {name: deepcopy(COMMAND_TEMPLATES.get(name, {})) for name in selected}


def protocol_catalog(commands: list[str] | tuple[str, ...] | None = None) -> dict[str, Any]:
    selected = list(commands or SUPPORTED_COMMANDS)
    return {
        "note": "Recipes use point.goto and do not depend on motor presets. Preset commands are exposed only as direct protocol utilities.",
        "commands": selected,
        "templates": command_templates(tuple(selected)),
        "enums": deepcopy(COMMAND_ENUMS),
        "lens_actions": COMMAND_ENUMS["action"],
        "device_queries": COMMAND_ENUMS["type"],
        "scan_modes": ["vendor", "zone"],
        "home_after_actions": COMMAND_ENUMS["home_action"],
        "dangerous_commands_require_confirm": list(DANGEROUS_COMMANDS),
        "group_guide": deepcopy(COMMAND_GROUP_GUIDE),
        "command_guide": deepcopy(COMMAND_GUIDE),
    }
